import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class NftsService {
  constructor(private prisma: PrismaService) {}

  /**
   * Get NFT tracing information (invite code chain)
   * @param nftId NFT ID
   * @returns Tracing information
   */
  async traceNFT(nftId: number) {
    const record = await this.prisma.nftRecord.findUnique({
      where: { nftId },
      include: {
        inviteCode: {
          include: {
            parentInviteCode: true,
          },
        },
        rootInviteCode: true,
      },
    });

    if (!record) {
      throw new NotFoundException('NFT record not found');
    }

    // Build invite code chain
    const chain = [];
    let currentInviteCode = record.inviteCode;
    
    while (currentInviteCode) {
      chain.push({
        id: currentInviteCode.id,
        code: currentInviteCode.code,
        level: currentInviteCode.level,
        applicantAddress: currentInviteCode.applicantAddress,
      });
      
      if (currentInviteCode.parentInviteCodeId) {
        currentInviteCode = await this.prisma.inviteCode.findUnique({
          where: { id: currentInviteCode.parentInviteCodeId },
          include: { parentInviteCode: true },
        });
      } else {
        break;
      }
    }

    return {
      nftId: record.nftId,
      ownerAddress: record.ownerAddress,
      mintedAt: record.mintedAt,
      inviteCodeChain: chain.reverse(), // From root to current
      rootInviteCode: record.rootInviteCode,
      rootApplicantAddress: record.rootApplicantAddress,
    };
  }

  /**
   * Get all NFTs generated by root invite code
   * @param rootInviteCodeId Root invite code ID
   * @returns Array of NFTs
   */
  async getNFTsByRootInviteCode(rootInviteCodeId: number) {
    return this.prisma.nftRecord.findMany({
      where: { rootInviteCodeId },
      include: {
        inviteCode: true,
      },
    });
  }

  /**
   * Get all NFTs of a user
   * @param address User address
   * @returns Array of NFTs
   */
  async getNFTsByUser(address: string) {
    return this.prisma.nftRecord.findMany({
      where: { ownerAddress: address.toLowerCase() },
      include: {
        inviteCode: true,
        rootInviteCode: true,
      },
    });
  }
}

